Dodson/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from lineup_test_2 import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index),
    url(r'^lineup_test_2/', include('lineup_test_2.urls')),
]

lineup_test_2/urls.py
from django.conf.urls import url
from . import views

app_name = 'lineup_test_2'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^create_new_user/$', views.create_new_user, name='create_new_user'),
    url(r'^test_dir/(?P<uid>([A-Z]|[0-9]){14})/$', views.test_dir, name='test_dir'),
    # url(r'^generate_question/(?P<uid>([A-Z]|[0-9]){14})/(?P<category>(O1|Omany|R|U1|F))/$', views.generate_question, name='generate_question'),

    url(r'^generate_question/(?P<uid>([A-Z]|[0-9]){14})/$', views.generate_question, name='generate_question'),
    url(r'^detail/(?P<uid>([A-Z]|[0-9]){14})/(?P<category>(O1|Omany|R|U1|F))/$', views.detail, name='detail'),
    url(r'^record/(?P<uid>([A-Z]|[0-9]){14})/(?P<category>(O1|Omany|R|U1|F))/(?P<a>(0|20|40|60|80|100))/$', views.record_answer, name='record_answer'),

    url(r'^instruction/(?P<uid>([A-Z]|[0-9]){14})/(?P<mode>([0-9]))/$', views.instruction, name='instruction'),
    url(r'^example/(?P<uid>([A-Z]|[0-9]){14})/$', views.example, name='example'),

    url(r'^submit/(?P<uid>([A-Z]|[0-9]){14})/$', views.submit_survey, name='submit_survey'),

    url(r'^record_ex/(?P<uid>([A-Z]|[0-9]){14})/(?P<a>(0|20|40|60|80|100))/$',
        views.record_example, name='record_example'),

    # url(r'^final_page/(?P<uid>([A-Z]|[0-9]){14})/$',
    #     views.record_example, name='record_example'),

]

lineup_test_2/models.py
from django.db import models


# Create your models here.
class EyewitnessStimuli(models.Model):

    CONFIDENCE_SCORE = ( (60, 60), (80, 80), (100, 100), )
    LINEUP_RACE = (('B', 'black'), ('W', 'white'), )
    LINEUP_NUMBER = (
        ('B1', 'B1'), ('B2', 'B2'), ('B3', 'B3'), ('B4', 'B4'), ('B5', 'B5'), ('B6', 'B6'),
        ('W1', 'W1'), ('W2', 'W2'), ('W3', 'W3'), ('W4', 'W4'), ('W5', 'W5'), ('W6', 'W6'),
    )
    CATEGORY = (('O1', 'O1'), ('Omany', 'Omany'), ('R', 'R'), ('U1', 'U1'), ('F', 'F'), )
    CHOICE = ((1, 1), (2, 2), (3, 3),(4, 4), (5, 5), (6, 6),)

    score = models.IntegerField(choices=CONFIDENCE_SCORE)
    lineup_race = models.CharField(max_length=1, choices=LINEUP_RACE)
    lineup_number = models.CharField(max_length=2, choices=LINEUP_NUMBER)
    category = models.CharField(max_length=10, choices=CATEGORY)
    statement = models.TextField(max_length=100)    # confidence statement and justification
    statementOnly = models.TextField(max_length=100)    # confidence statement only
    chosen_face = models.IntegerField(choices=CHOICE)
    lineup_order = models.CharField(max_length=14)

    def __str__(self):
        return self.category + "; " + self.lineup_number+"; "+ self.statement


class User(models.Model):
    # SEX = (('M', 'Male'), ('F', 'Female'))
    EX_CONFIDENCE_SCORE = ( (0, 0), (20, 20), (40, 40), (60, 60), (80, 80), (100, 100), )

    userId = models.CharField(max_length=14, primary_key=True)
    CATEGORY = (('O1', 'O1'), ('Omany', 'Omany'), ('R', 'R'), ('U1', 'U1'), ('F', 'F'), )

    # This field represent which lineup he will see.
    category = models.CharField(max_length=10, choices=CATEGORY)
    '''
    This field represent whether this user will see the statement and justification or statement only.
    if StatementType = true, user will see full statement (confidence statement and justification)
    if StatementType = false, user will see statement only
    '''
    StatementType = models.BooleanField()
    example_response = models.IntegerField(choices=EX_CONFIDENCE_SCORE, null=True)

    sex = models.CharField(max_length=1, null=True)
    birth_year = models.IntegerField(null=True)
    race = models.CharField(max_length=10, null=True)
    device = models.CharField(max_length=10, null=True)
    comments = models.CharField(max_length=100, null=True)

    def category_func(self):
        return self.category
    category_func.short_description = "assigned category"

    def statement_type(self):
        return self.StatementType
    statement_type.boolean = True

    def example_answer(self):
        return self.example_response

    def __str__(self):
        return self.userId


class Response(models.Model):
    CONFIDENCE_SCORE = ( (0, 0), (20, 20), (40, 40), (60, 60), (80, 80), (100, 100), )

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(EyewitnessStimuli, on_delete=models.CASCADE)
    answer = models.IntegerField(choices=CONFIDENCE_SCORE, null=True)

    # category = models.CharField(max_length=10, choices=CATEGORY)
    def user_id(self):
        return self.user.userId

    def example_answer(self):
        return self.user.example_response

    def question_category(self):
        return self.question.category
    question_category.short_description = 'category'

    def question_lineup_number(self):
        return self.question.lineup_number
    question_lineup_number.short_description = 'lineup_number'

    def statement_type(self):
        return self.user.StatementType
    statement_type.boolean = True

    def statement(self):
        if self.user.StatementType:
            return self.question.statement
        else:
            return self.question.statementOnly

    def __str__(self):
        return "{uid:}; Category: {cate:}; Lineup Number: {lineup_num:}; Statement Type: {stmtOnly:}"\
            .format(uid=self.user.userId, cate=self.question.category, lineup_num=self.question.lineup_number, stmtOnly=self.user.StatementType)


class SecretCode(models.Model):
    code = models.CharField(max_length=14)
    valid = models.BooleanField(default=False)

    def validity(self):
        return self.valid
    validity.short_description = 'Valid?'
    validity.boolean = True

lineup_test_2/views.py
import random
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.views import generic
import uuid
from lineup_test_2.models import User, EyewitnessStimuli, Response, SecretCode
from Site_Config.models import SiteSetting


# Create your views here.
def index(request):

    return render(request, 'lineup_test_2/index.html')


def create_new_user(request):
    STATEMENT_TYPE = [True, False]
    CATEGORY = ['O1', 'Omany', 'R', 'U1', 'F']
    config = SiteSetting.load()
    limit = config.response_limit
    threshold = config.manipulation_check_threshold

    choice_dict = {}  # choice dict
    for c in CATEGORY:
        for b in STATEMENT_TYPE:
            q_set = User.objects.filter(category=c, StatementType=b, example_response__gt=threshold) \
                .exclude(response__answer__isnull=True)
            if len(q_set) < limit:
                if c not in choice_dict:
                    choice_dict[c] = [b]
                else:
                    choice_dict[c].append(b)
    # print(choice_dict)
    if len(choice_dict) == 0:
        return HttpResponse("Thank you for participating this survey!\n The survey has ended.")

    category_list = ['O1', 'Omany', 'R', 'U1', 'F']

    uid = uuid.uuid4().hex[:14].upper()
    while User.objects.filter(pk=uid).exists():
        uid = uuid.uuid4().hex[:14].upper()

    random_category = random.choice(list(choice_dict.keys()))
    random_stmt_type = random.choice(choice_dict[random_category])

    new_user = User(userId=uid, StatementType=random_stmt_type, category=random_category)
    new_user.save()

    # return HttpResponseRedirect(reverse('lineup_test_2:test_dir', args=(uid,)))
    return HttpResponseRedirect(reverse('lineup_test_2:instruction', args=(uid, 1)))


def test_dir(request, uid):
    context = {
        'uid': uid,
    }
    """
    user = get_object_or_404(User, pk=uid)

    # removed by lz, on 08/08
    # category_list = EyewitnessStimuli.objects.values('category').distinct()
    lineup_category = [user.category]


    count = 0
    finished = True
    # removed by lz, on 08/08
    # for cate in ["O1", "Omany", "R"]:
    for cate in lineup_category:
        # q_set = user.response_set.filter(category=cate)
        q_set = user.response_set.all()
        if len(q_set) == 0: # test has not been generated yet.
            finished = False
            break

        # q_set = user.response_set.filter(category=cate).filter(answer__isnull=True)
        q_set = user.response_set.all().filter(answer__isnull=True)
        # print(len(q_set))
        count += len(q_set)

    # print(count)
    if finished and count == 0:
        context = generate_survey_content(context)
        return render(request, 'lineup_test_2/survey.html', context)
    else:
        # removed by lz, on 08/08
        # context['category_list'] = category_list
        context['category_list'] = lineup_category
        return render(request, 'lineup_test_2/test_dir.html', context)
    """
    context = generate_survey_content(context)
    return render(request, 'lineup_test_2/survey.html', context)


def generate_question(request, uid):
    user = get_object_or_404(User, pk=uid)
    lineup_category = user.category
    q_set = user.response_set.all()
    if len(q_set) != 0:
        return HttpResponseRedirect(reverse('lineup_test_2:detail', args=(uid, lineup_category,)))
    query_set_cate = EyewitnessStimuli.objects.filter(category=lineup_category)
    race_set = ['W', 'B']
    question_set = []

    for race in race_set:
        chosen_set = []  # track lineup_number that has been used
        query_set = query_set_cate.filter(lineup_race=race)
        if len(query_set) == 3:
            for q in query_set:
                question_set.append(q)
        else:
            for _ in range(3):
                for n in chosen_set:
                    query_set = query_set.exclude(lineup_number=n)
                q = random.choice(query_set)
                question_set.append(q)
                chosen_set.append(q.lineup_number)

    order = [0, 1, 2, 3, 4, 5]
    random.shuffle(order)
    user = User(userId=uid)

    for n in order:
        response = Response(user=user, question=question_set[n])
        response.save()
    '''
    user = get_object_or_404(User, pk=uid)
    q_set = user.response_set.filter(category=category)
    if len(q_set) != 0:
        return HttpResponseRedirect(reverse('lineup_test_2:detail', args=(uid, category,)))

    chosen_set = []     # track lineup_number that has been used
    score_set = [60,80,100]
    race_set = ['W', 'B']

    question_set = []

    query_set_cate = EyewitnessStimuli.objects.filter(category=category)

    for i in range(6):
        query_set = query_set_cate.filter(score=score_set[int(i/2)], lineup_race=race_set[int(i % 2)])
        for n in chosen_set:
            query_set = query_set.exclude(lineup_number=n)

        q = random.choice(query_set)
        question_set.append(q)
        chosen_set.append(q.lineup_number)

    order = [0,1,2,3,4,5]
    random.shuffle(order)
    user = User(userId=uid)
    for n in order:
        response = Response(user=user, question=question_set[n], category=category)
        response.save()
    return HttpResponseRedirect(reverse('lineup_test_2:detail', args=(uid, category,)))
    '''
    return HttpResponseRedirect(reverse('lineup_test_2:detail', args=(uid, lineup_category,)))


def detail(request, uid, category):
    user = get_object_or_404(User, pk=uid)
    # q_set = user.response_set.filter(category=user.category).exclude(answer__isnull=True)
    q_set = user.response_set.all().exclude(answer__isnull=True)

    q_num = len(q_set)
    # print(q_num)

    statement_type = user.StatementType

    if q_num == 6:
        context = {
            'uid': uid,
            'mode': 3,
        }
        # return render(request, 'lineup_test_2/instruction.html', context)
        return HttpResponseRedirect(reverse('lineup_test_2:instruction', args=(uid, 3)))
    else:
        response = Response.objects.filter(user=user)[q_num]
        sample_q = response.question

        file_path = 'lineup_test_2/lineups/'
        lineup_number = sample_q.lineup_number
        if lineup_number[0] == 'W':
            file_path += 'faces_white/' + lineup_number[1] + '/'
        else:
            file_path += 'faces_black/' + lineup_number[1] + '/'

        lineup_order = sample_q.lineup_order.split(';')
        img_set_path = []
        chosen_face = ""
        for image_num in lineup_order:
            if int(image_num) == sample_q.chosen_face:
                chosen_face = file_path + image_num + '.jpg'

            img_set_path.append(file_path + image_num + '.jpg')

        if statement_type:
            stmt = sample_q.statement
        else:
            stmt = sample_q.statementOnly

        chosen_face = file_path + '5.jpg'

        context = {
            # 'sample' : sample_q,
            # 'image_path': file_path,
            'chosen': chosen_face,
            'lineup_order1': img_set_path[:3],
            'lineup_order2': img_set_path[3:],
            'statement': stmt,
            'uid': uid,
            'category': category,
        }
        return render(request, 'lineup_test_2/detail.html', context)


def record_answer(request, uid, category, a):

    # print(a)
    user = get_object_or_404(User, pk=uid)
    # q_set = user.response_set.filter(category=category).exclude(answer__isnull=True)
    q_set = user.response_set.all().exclude(answer__isnull=True)
    q_num = len(q_set)

    # response = Response.objects.filter(user=user, category=category)[q_num]
    response = Response.objects.filter(user=user)[q_num]
    response.answer = a
    response.save()

    return HttpResponseRedirect(reverse('lineup_test_2:detail', args=(uid, category)))


def instruction(request, uid, mode):
    # print (mode)
    context = {
        'mode': mode,
        'uid': uid,
    }
    return render(request, 'lineup_test_2/instruction.html', context)


def example(request, uid):
    return render(request, 'lineup_test_2/example.html', context={'uid':uid})


def submit_survey(request, uid):
    # print(request)
    # print(request.POST.get("sex"))
    # print(request.POST.get("birthyear"))
    # print(request.POST.get("device"))
    # print(request.POST.get("race"))

    user = get_object_or_404(User, pk=uid)
    user.sex = request.POST.get("sex")
    user.birth_year = request.POST.get("birthyear")
    user.device = request.POST.get("device")
    user.race = request.POST.get("race")
    user.comments = request.POST.get("comment")[:100]
    user.save()

    codes = SecretCode.objects.filter(valid=True)
    if len(codes) >= 1:
        code = random.choice(codes).code
    else:
        code = None
    # return HttpResponse("Thank you for participating this survey!\n You may now close your browser.")
    return render(request, 'lineup_test_2/final_page.html', context={'code':code})


def generate_survey_content(context):
    b_year = [i for i in range(1900,2018)]
    b_year.reverse()
    race = ['Whte/Caucasian', 'Black/African-American', 'Hispanic', 'Asian/Pacific Islander', 'Other']
    device = ['desktop', 'laptop', 'iphone/smartphone', 'ipad/tablet']
    context['year_list'] = b_year
    context['race_list'] = race
    context['device_list'] = device

    return context


def record_example(request, uid, a):
    user = get_object_or_404(User, pk=uid)
    user.example_response = a
    user.save()

    return HttpResponseRedirect(reverse('lineup_test_2:instruction', args=(uid, 2)))

lineup_test_2/templates/lineup_test_2/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Test</title>
    <link rel="stylesheet"  href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'lineup_test_2/style.css' %}" />
</head>
<body>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    {% load static %}
    <div class="container">
        <!-- <table style="width:100%"> -->
        <div class="row">
            {% for path in lineup_order1 %}
                {% if path == chosen %}
                    <img id="chosen" src="{%  static path %}" class="img-responsive image1">
                {% else %}
                    <img src="{%  static path %}" class="img-responsive image1">
                {% endif %}
            {% endfor %}
        </div>

        <div class="row">
            {% for path in lineup_order2 %}
                {% if path == chosen %}
                    <img id="chosen" src="{%  static path %}" class="img-responsive image1">
                {% else %}
                    <img src="{%  static path %}" class="img-responsive image1">
                {% endif %}
            {% endfor %}
        </div>
    <!--</center>-->
    </div>
    <div class="container text-center">
        <h1 style="background-color: lightgoldenrodyellow; color: red">{{ statement }}</h1>
    </div>

    <br>

    <br>
    <div class="container">
        <div class="row text-center">
            <p class="lead">
                <b>Translate the written expression of certainty above onto the following numeric scale:</b>
                <br>
            </p>
        </div>
        <div class="row">
            <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2 text-center">
                <p class="lead"> Not at All Certain</p>
            </div>
            <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
                <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
                    <form action="{% url 'lineup_test_2:record_answer' uid category 0 %}">
                        <input type="submit" class="btn btn-primary btn-lg" style="width:100%" value="0%"/>
                    </form>
                </div>
                <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
                    <form action="{% url 'lineup_test_2:record_answer' uid category 20 %}">
                        <input type="submit" class="btn btn-primary btn-lg" style="width:100%" value="20%"/>
                    </form>
                </div>
                <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
                    <form action="{% url 'lineup_test_2:record_answer' uid category 40 %}">
                        <input type="submit" class="btn btn-primary btn-lg" style="width:100%" value="40%"/>
                    </form>
                </div>

                <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
                    <form action="{% url 'lineup_test_2:record_answer' uid category 60 %}">
                        <input type="submit" class="btn btn-primary btn-lg" style="width:100%" value="60%"/>
                    </form>
                </div>
                <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
                    <form action="{% url 'lineup_test_2:record_answer' uid category 80 %}">
                        <input type="submit" class="btn btn-primary btn-lg" style="width:100%" value="80%"/>
                    </form>
                </div>
                <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
                    <form action="{% url 'lineup_test_2:record_answer' uid category 100 %}">
                        <input type="submit" class="btn btn-primary btn-lg" style="width:100%" value="100%"/>
                    </form>
                </div>
            </div>
            <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2 text-center">
                <p class="lead"> Completely Certain</p>
            </div>
        </div>
    </div>
    <br>
    <br>
    <br>
    <br>
</body>
</html>

lineup_test_2/templates/lineup_test_2/example.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Example</title>
    <link rel="stylesheet"  href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'lineup_test_2/style.css' %}" />
</head>
<body>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    {% load static %}
    <div class="container">
        <div class="page-header">
            <h1>
                This is an example of the Test
            </h1>
        </div>

        <!-- <table style="width:100%"> -->
        <div class="row">
            <img src="/static/lineup_test_2/lineups/smiley/1.jpg" class="img-responsive image1">
            <img src="/static/lineup_test_2/lineups/smiley/2.jpg" class="img-responsive image1">
            <img src="/static/lineup_test_2/lineups/smiley/3.jpg" class="img-responsive image1">
        </div>

        <div class="row">
            <img src="/static/lineup_test_2/lineups/smiley/4.jpg" class="img-responsive image1">
            <img id="chosen" src="/static/lineup_test_2/lineups/smiley/5.jpg" class="img-responsive image1">
            <img src="/static/lineup_test_2/lineups/smiley/6.jpg" class="img-responsive image1">
        </div>
    <!--</center>-->
    </div>
    <div class="container text-center">
        <h1 style="background-color: lightgoldenrodyellow; color: red">I am completely certain this was the smiley face I saw earlier.</h1>
    </div>

    <br>

    <br>
    <div class="container">
        <div class="row text-center">
            <p class="lead">
                <b>Translate the written expression of certainty above onto the following numeric scale:</b>
                <br>
            </p>
        </div>
        <div class="row">
            <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2 text-center">
                <p class="lead"> Not at All Certain</p>
            </div>
            <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
                <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
                    <form action="{% url 'lineup_test_2:record_example' uid 0 %}">
                        <input type="submit" class="btn btn-primary btn-lg" style="width:100%" value="0%"/>
                    </form>
                </div>
                <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
                    <form action="{% url 'lineup_test_2:record_example' uid 20 %}">
                        <input type="submit" class="btn btn-primary btn-lg" style="width:100%" value="20%"/>
                    </form>
                </div>
                <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
                    <form action="{% url 'lineup_test_2:record_example' uid 40 %}">
                        <input type="submit" class="btn btn-primary btn-lg" style="width:100%" value="40%"/>
                    </form>
                </div>

                <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
                    <form action="{% url 'lineup_test_2:record_example' uid 60 %}">
                        <input type="submit" class="btn btn-primary btn-lg" style="width:100%" value="60%"/>
                    </form>
                </div>
                <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
                    <form action="{% url 'lineup_test_2:record_example' uid 80 %}">
                        <input type="submit" class="btn btn-primary btn-lg" style="width:100%" value="80%"/>
                    </form>
                </div>
                <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
                    <form action="{% url 'lineup_test_2:record_example' uid 100 %}">
                        <input type="submit" class="btn btn-primary btn-lg" style="width:100%" value="100%"/>
                    </form>
                </div>
            </div>
            <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2 text-center">
                <p class="lead"> Completely Certain</p>
            </div>
        </div>

        <br>

{#        <div class="row">#}
{#            <form action="{% url 'lineup_test_2:instruction' uid 2 %}">#}
{#                <input type="submit" value="Continue"  class="btn btn-primary btn-lg center-block"/>#}
{#            </form>#}
{#        </div>#}
    </div>
    <br>
    <br>
    <br>
    <br>
</body>
</html>

lineup_test_2/templates/lineup_test_2/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet"  href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <title>Welcome Page</title>
</head>
<body>
    <!-- Begin page content -->
    <div class="jumbotron text-center">
        <h1>Dodson Cognition Lab</h1>
        <p>Welcome to take this memory test</p>
    </div>
    <div class="container">
        <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 col-md-offset-2 col-lg-offset-2">
            <div class="page-header">
                <h1>
                    About This Test
                </h1>
            </div>

            <p class="lead">
                You are invited to participate in a research study about memory.
                The survey is being conducted by Chad Dodson, PhD, from the Department of Psychology at the University of Virginia.
                The survey should take 5 minutes to complete. Your responses will be kept confidential.
                You may drop out of the study at any time by closing this browser window.
            </p>
            <br>
            <p><b>Please read the following consent agreement before continuing:</b></p>

            {% load static %}
            <iframe src={% static "consent_agreement.html"%} width="100%"></iframe>
            <br>
            <br>
            <form action="{% url 'lineup_test_2:create_new_user' %}">
                <input type="submit" value="I Agree to Continue"  class="btn btn-primary btn-lg center-block"/>
            </form>
            <br>
            <br>
            <br>
            <br>
        </div>
    </div>
</body>
</html>

lineup_test_2/templates/lineup_test_2/instruction.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet"  href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <title>Instruction</title>
</head>
<body>
    <div class="container">
        <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 col-md-offset-2 col-lg-offset-2">
            <div class="page-header">
                <h1>
                    Instruction
                </h1>
            </div>
            {% if mode == '1' %}
                <p class="lead">
                    Pretend you are a police officer. You will see several lineups of faces.
                    In each lineup, an eyewitness has identified a face as the suspect.
                    The chosen face is highlighted in <strong style="color: red;">red</strong>.
                    You also will see the eyewitness’s written expression of certainty about their decision.
                </p>

                <p class="lead">
                    Your task is to translate the written expression onto a numeric confidence scale.
                    Before beginning the task, you will be shown an example involving a yellow smiley face
                    that was definitely seen before by the eyewitness.
                </p>

                <form action="{% url 'lineup_test_2:example' uid %}">
                    <input type="submit" value="I Agree to Continue"  class="btn btn-primary btn-lg center-block"/>
                </form>
            {% elif mode == '2' %}
                <p class="lead">
                    You will now proceed to the real lineups.
                </p>
                <form action="{% url 'lineup_test_2:generate_question' uid %}">
                    <input type="submit" value="Continue"  class="btn btn-primary btn-lg center-block"/>
                </form>
            {% elif mode == '3' %}
                <p class="lead">
                    You have finished with this portion of the survey.
                </p>
                <form action="{% url 'lineup_test_2:test_dir' uid %}">
                    <input type="submit" value="Continue"  class="btn btn-primary btn-lg center-block"/>
                </form>
            {% endif %}
        </div>
    </div>
</body>
</html>

lineup_test_2/templates/lineup_test_2/test_dir.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet"  href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <title>Test Directory</title>
</head>
<body>

    <div class="container">
        <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 col-md-offset-2 col-lg-offset-2">
            <div class="page-header">
                <h1>
                    Test Directory
                </h1>
            </div>

            {% if category_list %}
                {% for category in category_list %}
                        <form action="{% url 'lineup_test_2:generate_question' uid category %}">
                            <input type="submit" value={{ category }}  class="btn btn-lg btn-default btn-block"/>
                        </form>
                    <br>
                {% endfor %}
            {% else %}
                <p>No category are available.</p>
            {% endif %}

        </div>
    </div>


</body>
</html>